# ----------------------------------------
#  Brewfile
# ----------------------------------------
tap "homebrew/cask"
tap "homebrew/bundle"
tap "homebrew/services"
cask_args appdir: "/Applications"

# ========== General Tools ==========
brew "git"
brew "ghq"
brew "peco"
brew "tree"
brew "exa"
brew "wget"

# ========== App Tools ==========
brew "awscli"
brew "jmeter"
brew "vegeta"

brew "tfenv"
brew "tflint"

brew "nodebrew"

# ========== Languages ==========
brew "go"

# ========== Applications ==========
cask "clipy"
cask "shiftit"
cask "slack"
cask "docker"
cask "kindle"
cask "iterm2"
cask "figma"
cask "zoomus"
cask "postman"
cask "cyberduck"
cask "gpg-suite"
cask "chromedriver"
cask "google-chrome"
cask "visual-studio-code"
cask "google-japanese-ime"
cask "deepl"
cask "obs"
cask "obs-virtualcam"
cask "tableplus"
cask "notion"
mas "CotEditor", id: 1024640650